### ISSUE TITLE
Sequential recommendation & data format

### ISSUE THREAD

**Issue by cass12** [massquantity/LibRecommender#193]
Hi there, I have couple of questions 

1.What does the label column mean? Couldn't find any explanation in user guide.
2. Implying GRU4Rec can be used for sequential recommendations, is this feature currently available for this model? 

Thanks a lot!

**Comment by massquantity** [comment]
Since GRU4Rec can only deal with implicit dataset, label is 1 for positive samples and 0 for negative samples. If your data only contains positive samples, you can set all the labels to 1 and do negative sampling afterwards.

Yes sequential recommendation is available. For the data format described in User Guide, LibRecommender will transform the data into user interacted sessions internally, which is used in training.

**Comment by cass12** [comment]
Regarding the label question, got it, thanks a lot! 

What is still unclear to me is: 
You said the model transforms user-item interactions into user sessions internally. So when making recommendations, the model takes into consideration all user history until the present moment? 

Maybe I wasn't concise enough, but I meant something like this for eg:
Being given an user id x, items interacted with (let's say 1,2,3), I wanna predict what items the user might interact with in this session.

Thanks in advance!

**Comment by massquantity** [comment]
The model will use a user's last `n` interacted items in data for recommendation. `n` is a hyper-parameter, and in GRU4Rec the parameter is `recent_num`. 

For now models in LibRecommender can't make recomendation based on a user's arbitrary item sequence. Maybe it will be added in the future cuz a few people have asked similar questions.

**Comment by cass12** [comment]
Got it, thanks a lot! 

One final question: while using my own dataset (in the specified format in user guide) and trying to train a RNN model, it just hangs at training stage, without any progress, like below. Any clue why would this happen?

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/64856925/216064249-39ecb414-3bef-400b-9b10-c09e4600b728.png">

**Comment by massquantity** [comment]
This is weird. Can you post all your code here? And how many data do you have?
Or you can send me some sample data, so that I can reproduce the problem.

**Comment by cass12** [comment]
I am using the pure_ranking_example.py to run an experiment, the only difference being my dataset. 
Funny enough, it works with your file, so it's probably not a Mac M1 (which I am using) issue as I thought. 

Here is the dataset I'm using: 
[sample_data.csv](https://github.com/massquantity/LibRecommender/files/10567598/sample_data.csv)

**Comment by massquantity** [comment]
Ok i've finally figured out what's going on here. This is like a "half bug". 
The model tries to sample unique items to build sessions from a user's interaction history. But the problem is, it is based on the assumption that the user's history items are all different.

Your data contains duplicate samples, which is common in that a user may have clicked an item multiple times. But the sampling process may end up with an infinite loop since it can't get enough unique items. You can use functions like `drop_duplicates` in Pandas before training.

I'll release a new version, which can remove duplicate items in user history internally.

**Comment by cass12** [comment]
Thanks a lot for the quick reply and all of your help! :)

**Comment by massquantity** [comment]
Sequential recommendation has been supported in version 1.1.0
