### ISSUE TITLE
Cold start recommendations results by new users are not the same

### ISSUE THREAD

**Issue by vanessm** [massquantity/LibRecommender#319]
Hello, I have used LightGCN algorithm for having collaborative filtering recommendations on purchase history data.
And for each new customer (which are present in database but which are not already purchased products), I have seen that recommendations are differents.
Is it normal ?
Here my code : 
`purchase_counts = purchase_history.groupby(['client_id', 'article_id', 'date_commande'], as_index=False)['quantité'].mean().rename(columns={'quantité':'purchase_count'}).reset_index(drop=True)
purchase_counts['client_id'] = purchase_counts['client_id'].astype('int64')
purchase_counts['article_id'] = purchase_counts['article_id'].astype('int64')
purchase_counts['date_commande'] = pd.to_datetime(purchase_counts['date_commande'], format=('%Y-%m-%d %H:%M:%S')).view('int64')
purchase_counts['purchase_count'] = purchase_counts['purchase_count'].astype('int64')

data = purchase_counts.rename(columns={'client_id': 'user', 'article_id': 'item', 'purchase_count':'label', 'date_commande':'time'})
train_data, eval_data, test_data = random_split(data, multi_ratios=[0.8, 0.1, 0.1])

train_data, data_info = DatasetPure.build_trainset(train_data)
eval_data = DatasetPure.build_evalset(eval_data)
test_data = DatasetPure.build_testset(test_data)
print(data_info)  # n_users: 4658, n_items: 7600, data sparsity: 1.0526 %

lightgcn = LightGCN(
    task="ranking",
    data_info=data_info,
    loss_type="bpr",
    embed_size=16,
    n_epochs=1,
    lr=1e-3,
    batch_size=2048,
    num_neg=1,
    device="cuda",
)

lightgcn.fit(
    train_data,
    neg_sampling=True,
    verbose=2,
    eval_data=eval_data,
    metrics=["loss", "roc_auc", "precision", "recall", "ndcg"],
)

evaluate(
    model=lightgcn,
    data=test_data,
    neg_sampling=True,
    metrics=["loss", "roc_auc", "precision", "recall", "ndcg"],
)`
PS : I have used implicit feedback by calculating average quantity purchase by customer, product and purchase date

Another question : I have a value very big according to other for pseudo-rating how can I ponderate it ?
Thanks in advance.

**Comment by massquantity** [comment]
Hi, your observation is correct. The recommendations for new customers are randomly selected from products with the highest prediction scores. Because I don't think it's a good idea to recommend same items for every new customer. But I don't know, maybe I'm wrong :)

```
Another question: I have a value very big according to other for pseudo-rating how can I ponderate it?
```
If I understand the question correctly, you want to add weights to the data, and the weights are purchase_count? If so, this is not supported in this library.

However, there is an indirect way. You can treat purchase_count as a dense feature and feed it into the model. But in this case, you can't use LightGCN since it's a pure algorithm.
