### ISSUE TITLE
def rank_recommendations

### ISSUE THREAD

**Issue by vincm1** [massquantity/LibRecommender#374]
Hi, can you please explain how to use the stated formula to give a top10 item recommendation list for a specific user. I used NCF for implicit data.

**Comment by massquantity** [comment]
Sorry, i don't understand your question, what is the stated formula? Do you want to me to explain the [rank_recommendations](https://github.com/massquantity/LibRecommender/blob/master/libreco/recommendation/ranking.py#L10) function?

**Comment by vincm1** [comment]
Yes, 
i set up an NCF model for ranking
model = NCF(
    "ranking",
    data_info=data_info,
    loss_type="cross_entropy",
    embed_size=64,
    n_epochs=10,
    lr=0.01,
    batch_size=256,
    sampler="random",
    num_neg=10,
    dropout_rate=0.5,
    hidden_units=(128, 64, 32, 16)
)

user_id = 3472
num_recommendations = 10
recs = model.recommend_user(user=user_id, n_rec=num_recommendations) -> {3472: array([35160, 75202, 75197, 44147, 44154, 68123, 21853, 34933, 45356,
        40939])} and got 10 recommendations for this specific user.

But since I want to produce a Top-N list, how can I use your [rank_recommendation ] function for this? 

Thank you very much in advance!

**Comment by massquantity** [comment]
`rank_recommendations` is an internal function used in the library, so it is not easy to use it directly. The input and return ids are all internal ids, so you have to convert them back and forth many times like this (simplified, not runnable code): 
```python
inner_user_id = data_info.user2id[user_id]
preds = model.predict(user=np.repeat(user_id, 10), item=[35160, 75202, 75197, 44147, 44154, 68123, 21853, 34933, 45356,40939])
ranked_ids = rank_recommendations(task="ranking", user_ids=[inner_user_id], model_preds=preds, n_rec=10, n_items=10, user_consumed={})
top_n_list = [data_info.id2user[i] for i in ranked_ids]
```

In fact, you don't need to use it since the `model.recommend_user` method will call `rank_recommendations` directly, so `{3472: array([35160, 75202, 75197, 44147, 44154, 68123, 21853, 34933, 45356, 40939])}` is the top-n list for this user.

**Comment by vincm1** [comment]
Thank you for clarifying!

**Comment by vincm1** [comment]
Thank you for clarifying!
