### ISSUE TITLE
Social Media Recommendation

### ISSUE THREAD

**Issue by Hilal-Urun** [massquantity/LibRecommender#57]
Hi, I want to ask that can I use libRecommender for social media content and network recommendation like Instagram Explore?

**Comment by massquantity** [comment]
Yes you can. Just get the behavior and feature of users and assemble them into corresponding data format.

**Comment by Hilal-Urun** [comment]
Okey, thanks a lot

**Comment by Hilal-Urun** [comment]
And I just want to ask that ,
1.	When we use collobrative filter which is named  pure in repo we can recommend the similar user right ?
2.     Do you think which algorithm is better for this purpose?
2.	When we use the feat model, is the mean that we are doing like content based recommendation?
3.	And lastly , according to the figure below , how can I specify these columns for example for social media reccommendation?
![image](https://user-images.githubusercontent.com/37075702/120322073-ae767000-c2ec-11eb-9be2-89937e1e5914.png)

**Comment by massquantity** [comment]
You purpose is recommending similar users? Then I may choose UserCF. But my advice is negligible since I'm not very familiar with social recommendation.

1. Yes it is possible, but different algorithms have different ways, and the library doesn't export such an API yet.
2. Actually both collaborative filter and content-based features are used in these models. Using sole content features usually can't achieve high accuracy.
3. If you want to recommend other users to the target user, you can treat the item as users that the target user has interacted. For example, user A has browsed photos of user B, C, D, and you want to make recommendation for user A. The data may looks like this.

| user | other user | label | user age | user gender | other user age | other user gender |
| ---- | ---------- | ----- | -------- | -------- | -------------- | -------------- |
| A    | B          | 1     | 12       | male     | 23             | male           |
| A    | C          | 1     | 12       | male     | 45             | female         |
| A    | D          | 1     | 12       | male     | 67             | female         |

Then the columns may have following format:
```python
sparse_col = ["user gender", "other user gender"]
dense_col = ["user age", "other user age"]
user_col = ["user gender", "user age"]
item_col = ["other user gender", "other user age"]
```

Note that in the library you should change the `other user` column name to `item` in pandas, because the code contains that assumption. Another point is that in this way the model actually want to recommend users that the target user may want to interact with, which means the recommended users are not necessarily similar users.

**Comment by Hilal-Urun** [comment]
I am grateful to you for explanation @massquantity  I got the idea thanks so much then I want to ask about one more thing about content part. In this data  table can we add also content information, such as user A follows the user B and it liked B's some fotos and I also want to recommend similar content, can I also add this part on the same table or I need to create another table for this purpose? Thansk for your time.

**Comment by massquantity** [comment]
In my imagination, the data may look like this:

| user | other user | label | following 1 | following 2 |  liked photo1 | liked photo2 | ... |
| ---- | ---------- | ----- | -------- | -------- | -------------- | -------------- | ------------- |
| A    | B          | 1     | B       | C      |  photo1 of B | photo2 of B | ... |
| A    | C          | 1     | B     | C          | photo1 of B | photo2 of B | ... |
| A    | D          | 1     | B       | C      | photo1 of B | photo2 of B | ... |

Yes you should create a new table and set the `item` column to content.

**Comment by Hilal-Urun** [comment]
I got it thanks a lot <3
