### ISSUE TITLE
Question: how to deal with higly perishable items

### ISSUE THREAD

**Issue by sandermanneke** [massquantity/LibRecommender#80]
Hi, my problem is best described as a movie recommendation for a phyical theater. Movies are played for a short period of time and are then no longer available, but there is a vast amount of data on older titles.

It is like a permenant cold start problem because nearly all of the previously consumed films are not available anymore - but on a user level they do have some similarity to newly added films that are on display. An average approach would really loose out on the deeper user preference relationships that are available.

So the youtube wide and deep algo is cut out for the reccomender, but I am looking for some help in dealing with the very dynamic items inventory.

The options I see are

1. I could always ignore availability on the item and then filter the predictions afterwards and take unavailbe out of the ranked list.
2. Update consumed items with all unavailable items for each user so they are not considered in the reccomender - but I dont know if that will impact the actual predictions (?).
3. switch to another algo like item to item reccomendations, but that feels a waste of the 'solved' state of the movie problem.

Any tips or thoughts would be much appreciated. Thanks!

**Comment by massquantity** [comment]
When making recommendation for a user, we compute prediction scores for every candidate item and rank them according to the corresponding scores, at least in this library. 

So I think option 2 is a good choice, and it will save a lot of computing time and resources by only considering the available movies. I don't kown which model you use, but I think in general the actual predictions will not be influenced because making predictions for each item is independent.
